# Домашнее задание «Библиотека numpy. Вычислительные задачи»

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
import numpy as np
N = int(input('Введите N: '))
array_N = np.arange(0, N)
list(reversed(array_N))

Введите N: 10


[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [6]:
diag_mat = np.diag(array_N)
print(diag_mat)

print('Сумма значений матрицы на диагонали= ',  np.trace(diag_mat))


[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
Сумма значений матрицы на диагонали=  45


# Задание 3
# Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [7]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array(  [4, 12, -3] )


np.linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True