# Домашнее задание «Библиотека numpy. Вычислительные задачи»

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
import numpy as np
N = int(input('Введите N: '))
array_N = np.arange(0, N)
list(reversed(array_N))

Введите N: 10


[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [6]:
diag_mat = np.diag(array_N)
print(diag_mat)

print('Сумма значений матрицы на диагонали= ',  np.trace(diag_mat))


[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
Сумма значений матрицы на диагонали=  45


# Задание 3
# Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [7]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array(  [4, 12, -3] )


np.linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

# Задание 4

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

In [ ]:
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
Матрица в виде numpy array

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [ ]:
На сайт заходит очередной посетитель, о покупках которого известно следующее:
    next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [ ]:
for user in users_stats:
    print(user)

In [ ]:
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
for user in users_stats:
    print(user)

In [18]:
import numpy as np

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )
# Применение функции cosine к каждой строке матрицы
l = [cosine(user, next_user_stats) for user in users_stats]
# Нахождение индекса элемента максимально приближенного к cos = 1
like_user = l.index(max(l))
print(f'Похожий пользователь: № {like_user} |{", ".join(map(str, (users_stats[like_user])))}|')

Похожий пользователь: № 7 |0, 1, 1, 0, 0, 0|
